awsRegion: ${region}

rbac:
  create: true
  serviceAccount:
    # This value should match local.k8s_service_account_name in locals.tf
    name: ${k8s_service_account_name}
    annotations:
      # This value should match the ARN of the role created by module.iam_assumable_role_admin in irsa.tf
      eks.amazonaws.com/role-arn: ${irsa_assumable_role_admin}

autoDiscovery:
  clusterName: ${cluster_name}
  enabled: true